from venv.config_gitignore import TOKEN_GITIGNORE, PASSWORD_POSTGRESQL_GITIGNORE, IP_MY_SERVER_GITIGNORE

TOKEN = TOKEN_GITIGNORE

PASSWORD_POSTGRESQL = PASSWORD_POSTGRESQL_GITIGNORE

IP_MY_SERVER = IP_MY_SERVER_GITIGNORE